version: '3'

env:
  GO_VERSION: 'go1.22'

tasks:
  setup:
    cmds:
      - echo $GO_VERSION
      - gvm install $GO_VERSION

  start:
    cmd: go run cmd/main.go

  start:dev:
    cmd: go run cmd/main.go
    watch: true
    

  tidy:
    cmd: go mod tidy
  fmt:
    cmd: go fmt ./...

  tag:
    cmds:
      - git tag v0.0.1
      - git push origin --tag



  test:
    cmd: go test ./... --v

  cover:
    cmd: go test ./... -coverprofile=coverage.out
  
  report:
    deps: [cover]
    cmd: go tool cover -html=coverage.out -o coverage.html

  coverage:
    # This command analyzes test coverage and checks if it meets 80% threshold
    # Using explicit path to awk to avoid path issues
    cmd: go tool cover -func coverage.out | grep "total:" | /usr/bin/awk '{print ((int($3) > 80) != 1) }'

  build:
    cmd: go build -o bin/main cmd/main.go

  curl:
    cmd: curl http://localhost:8080/hello

  start:prod:
    cmds:
      - task build
      - ./bin/main
