name: CI Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        check-latest: true
        cache: true

    - name: Setup go-task
      uses: pnorton5432/setup-task@v1
      with:
        task-version: 3.29.1

        
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Verify dependencies
      run: go mod verify
      
    - name: Run Tests
      run: task test
      
    - name: Run Coverage
      run: task coverage
      
    - name: Generate Report
      run: task report
      
    - name: Prepare Reports Directory
      run: |
        mkdir -p reports
        cp coverage.html reports/
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports
        retention-days: 7