name: CI Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        check-latest: true
        cache: true
        
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Verify dependencies
      run: go mod verify
      
    - name: Run Tests
      run: make test
      
    - name: Run Coverage
      run: make coverage
      
    - name: Generate Report
      run: make report
      
    - name: Prepare Reports Directory
      run: |
        mkdir -p reports
        cp cover.html reports/
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports
        retention-days: 7