name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Consider using a more stable branch name like 'main' or 'develop'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
      - name: Lint
        run: golangci-lint run

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Production
        uses: your-deployment-action@v1  # Replace with your deployment action
        with:
          # Provide necessary deployment parameters
          environment: production
          artifact: ${{ steps.build.outputs.api }}

outputs:
  api: ${{ steps.build.outputs.api }}